USE kanggutang;

TRUNCATE BASE_CATEGORIES_DATA_INFO;
TRUNCATE BASE_SUB_CATEGORIES_DATA_INFO;

INSERT INTO BASE_CATEGORIES_DATA_INFO(CATEGORIES_NAME,CREATION_DATE) VALUES ('ROLE_TYPE',NOW());
INSERT INTO BASE_CATEGORIES_DATA_INFO(CATEGORIES_NAME,CREATION_DATE) VALUES ('EARNING_TYPE',NOW());
INSERT INTO BASE_CATEGORIES_DATA_INFO(CATEGORIES_NAME,CREATION_DATE) VALUES ('EXPENSE_TYPE',NOW());



INSERT INTO BASE_SUB_CATEGORIES_DATA_INFO(CATEGORIES_DATA_INFO_ID,CATEGORIES_CODE,CATEGORIES_VALUE,CREATION_DATE) VALUES ((SELECT CATEGORIES_DATA_INFO_ID FROM BASE_CATEGORIES_DATA_INFO WHERE CATEGORIES_NAME = 'ROLE_TYPE'),'1','管理员',NOW());
INSERT INTO BASE_SUB_CATEGORIES_DATA_INFO(CATEGORIES_DATA_INFO_ID,CATEGORIES_CODE,CATEGORIES_VALUE,CREATION_DATE) VALUES ((SELECT CATEGORIES_DATA_INFO_ID FROM BASE_CATEGORIES_DATA_INFO WHERE CATEGORIES_NAME = 'ROLE_TYPE'),'2','普通用户',NOW());

INSERT INTO BASE_SUB_CATEGORIES_DATA_INFO(CATEGORIES_DATA_INFO_ID,CATEGORIES_CODE,CATEGORIES_VALUE,CREATION_DATE) VALUES ((SELECT CATEGORIES_DATA_INFO_ID FROM BASE_CATEGORIES_DATA_INFO WHERE CATEGORIES_NAME = 'EARNING_TYPE'),'1','贴药',NOW());
INSERT INTO BASE_SUB_CATEGORIES_DATA_INFO(CATEGORIES_DATA_INFO_ID,CATEGORIES_CODE,CATEGORIES_VALUE,CREATION_DATE) VALUES ((SELECT CATEGORIES_DATA_INFO_ID FROM BASE_CATEGORIES_DATA_INFO WHERE CATEGORIES_NAME = 'EXPENSE_TYPE'),'1','电费',NOW());