package com.kanggutang.dao;

import com.kanggutang.model.BaseSubCategoriesDataInfo;
import com.kanggutang.model.BaseSubCategoriesDataInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseSubCategoriesDataInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_sub_categories_data_info
     *
     * @mbggenerated
     */
    int countByExample(BaseSubCategoriesDataInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_sub_categories_data_info
     *
     * @mbggenerated
     */
    int deleteByExample(BaseSubCategoriesDataInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_sub_categories_data_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer subCategoriesDataInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_sub_categories_data_info
     *
     * @mbggenerated
     */
    int insert(BaseSubCategoriesDataInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_sub_categories_data_info
     *
     * @mbggenerated
     */
    int insertSelective(BaseSubCategoriesDataInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_sub_categories_data_info
     *
     * @mbggenerated
     */
    List<BaseSubCategoriesDataInfo> selectByExample(BaseSubCategoriesDataInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_sub_categories_data_info
     *
     * @mbggenerated
     */
    BaseSubCategoriesDataInfo selectByPrimaryKey(Integer subCategoriesDataInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_sub_categories_data_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BaseSubCategoriesDataInfo record, @Param("example") BaseSubCategoriesDataInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_sub_categories_data_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BaseSubCategoriesDataInfo record, @Param("example") BaseSubCategoriesDataInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_sub_categories_data_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseSubCategoriesDataInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_sub_categories_data_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseSubCategoriesDataInfo record);
}