package com.kanggutang.dao;

import com.kanggutang.model.BaseCategoriesDataInfo;
import com.kanggutang.model.BaseCategoriesDataInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseCategoriesDataInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_categories_data_info
     *
     * @mbggenerated
     */
    int countByExample(BaseCategoriesDataInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_categories_data_info
     *
     * @mbggenerated
     */
    int deleteByExample(BaseCategoriesDataInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_categories_data_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer categoriesDataInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_categories_data_info
     *
     * @mbggenerated
     */
    int insert(BaseCategoriesDataInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_categories_data_info
     *
     * @mbggenerated
     */
    int insertSelective(BaseCategoriesDataInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_categories_data_info
     *
     * @mbggenerated
     */
    List<BaseCategoriesDataInfo> selectByExample(BaseCategoriesDataInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_categories_data_info
     *
     * @mbggenerated
     */
    BaseCategoriesDataInfo selectByPrimaryKey(Integer categoriesDataInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_categories_data_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BaseCategoriesDataInfo record, @Param("example") BaseCategoriesDataInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_categories_data_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BaseCategoriesDataInfo record, @Param("example") BaseCategoriesDataInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_categories_data_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseCategoriesDataInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_categories_data_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseCategoriesDataInfo record);
}