package com.kanggutang.dao;

import com.kanggutang.model.EarningExpenseYear;
import com.kanggutang.model.EarningExpenseYearExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EarningExpenseYearMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning_expense_year
     *
     * @mbggenerated
     */
    int countByExample(EarningExpenseYearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning_expense_year
     *
     * @mbggenerated
     */
    int deleteByExample(EarningExpenseYearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning_expense_year
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer earningExpenseYearId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning_expense_year
     *
     * @mbggenerated
     */
    int insert(EarningExpenseYear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning_expense_year
     *
     * @mbggenerated
     */
    int insertSelective(EarningExpenseYear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning_expense_year
     *
     * @mbggenerated
     */
    List<EarningExpenseYear> selectByExample(EarningExpenseYearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning_expense_year
     *
     * @mbggenerated
     */
    EarningExpenseYear selectByPrimaryKey(Integer earningExpenseYearId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning_expense_year
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") EarningExpenseYear record, @Param("example") EarningExpenseYearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning_expense_year
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") EarningExpenseYear record, @Param("example") EarningExpenseYearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning_expense_year
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EarningExpenseYear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning_expense_year
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EarningExpenseYear record);
}