package com.kanggutang.dao;

import com.kanggutang.model.Earning;
import com.kanggutang.model.EarningExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EarningMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning
     *
     * @mbggenerated
     */
    int countByExample(EarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning
     *
     * @mbggenerated
     */
    int deleteByExample(EarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer earningId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning
     *
     * @mbggenerated
     */
    int insert(Earning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning
     *
     * @mbggenerated
     */
    int insertSelective(Earning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning
     *
     * @mbggenerated
     */
    List<Earning> selectByExample(EarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning
     *
     * @mbggenerated
     */
    Earning selectByPrimaryKey(Integer earningId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Earning record, @Param("example") EarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Earning record, @Param("example") EarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Earning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Earning record);
}