package com.kanggutang.dao;

import com.kanggutang.model.Expense;
import com.kanggutang.model.ExpenseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExpenseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbggenerated
     */
    int countByExample(ExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbggenerated
     */
    int deleteByExample(ExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer expenseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbggenerated
     */
    int insert(Expense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbggenerated
     */
    int insertSelective(Expense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbggenerated
     */
    List<Expense> selectByExample(ExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbggenerated
     */
    Expense selectByPrimaryKey(Integer expenseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Expense record, @Param("example") ExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Expense record, @Param("example") ExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Expense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Expense record);
}