package com.kanggutang.dao;

import com.kanggutang.model.PermissionRole;
import com.kanggutang.model.PermissionRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PermissionRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbggenerated
     */
    int countByExample(PermissionRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbggenerated
     */
    int deleteByExample(PermissionRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer permissionRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbggenerated
     */
    int insert(PermissionRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbggenerated
     */
    int insertSelective(PermissionRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbggenerated
     */
    List<PermissionRole> selectByExample(PermissionRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbggenerated
     */
    PermissionRole selectByPrimaryKey(Integer permissionRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PermissionRole record, @Param("example") PermissionRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PermissionRole record, @Param("example") PermissionRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PermissionRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PermissionRole record);
}