package com.kanggutang.model;

import java.io.Serializable;
import java.util.Date;

public class BaseCategoriesDataInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_categories_data_info.CATEGORIES_DATA_INFO_ID
     *
     * @mbggenerated
     */
    private Integer categoriesDataInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_categories_data_info.CATEGORIES_NAME
     *
     * @mbggenerated
     */
    private String categoriesName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_categories_data_info.CREATION_DATE
     *
     * @mbggenerated
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_categories_data_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_categories_data_info.CATEGORIES_DATA_INFO_ID
     *
     * @return the value of base_categories_data_info.CATEGORIES_DATA_INFO_ID
     *
     * @mbggenerated
     */
    public Integer getCategoriesDataInfoId() {
        return categoriesDataInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_categories_data_info.CATEGORIES_DATA_INFO_ID
     *
     * @param categoriesDataInfoId the value for base_categories_data_info.CATEGORIES_DATA_INFO_ID
     *
     * @mbggenerated
     */
    public void setCategoriesDataInfoId(Integer categoriesDataInfoId) {
        this.categoriesDataInfoId = categoriesDataInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_categories_data_info.CATEGORIES_NAME
     *
     * @return the value of base_categories_data_info.CATEGORIES_NAME
     *
     * @mbggenerated
     */
    public String getCategoriesName() {
        return categoriesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_categories_data_info.CATEGORIES_NAME
     *
     * @param categoriesName the value for base_categories_data_info.CATEGORIES_NAME
     *
     * @mbggenerated
     */
    public void setCategoriesName(String categoriesName) {
        this.categoriesName = categoriesName == null ? null : categoriesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_categories_data_info.CREATION_DATE
     *
     * @return the value of base_categories_data_info.CREATION_DATE
     *
     * @mbggenerated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_categories_data_info.CREATION_DATE
     *
     * @param creationDate the value for base_categories_data_info.CREATION_DATE
     *
     * @mbggenerated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_categories_data_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", categoriesDataInfoId=").append(categoriesDataInfoId);
        sb.append(", categoriesName=").append(categoriesName);
        sb.append(", creationDate=").append(creationDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}