package com.kanggutang.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class EarningExpenseYear implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column earning_expense_year.EARNING_EXPENSE_YEAR_ID
     *
     * @mbggenerated
     */
    private Integer earningExpenseYearId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column earning_expense_year.YEAR
     *
     * @mbggenerated
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column earning_expense_year.EARNING_YEAR
     *
     * @mbggenerated
     */
    private BigDecimal earningYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column earning_expense_year.EXPENSE_YEAR
     *
     * @mbggenerated
     */
    private BigDecimal expenseYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column earning_expense_year.CREATION_DATE
     *
     * @mbggenerated
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column earning_expense_year.LAST_UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table earning_expense_year
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column earning_expense_year.EARNING_EXPENSE_YEAR_ID
     *
     * @return the value of earning_expense_year.EARNING_EXPENSE_YEAR_ID
     *
     * @mbggenerated
     */
    public Integer getEarningExpenseYearId() {
        return earningExpenseYearId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column earning_expense_year.EARNING_EXPENSE_YEAR_ID
     *
     * @param earningExpenseYearId the value for earning_expense_year.EARNING_EXPENSE_YEAR_ID
     *
     * @mbggenerated
     */
    public void setEarningExpenseYearId(Integer earningExpenseYearId) {
        this.earningExpenseYearId = earningExpenseYearId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column earning_expense_year.YEAR
     *
     * @return the value of earning_expense_year.YEAR
     *
     * @mbggenerated
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column earning_expense_year.YEAR
     *
     * @param year the value for earning_expense_year.YEAR
     *
     * @mbggenerated
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column earning_expense_year.EARNING_YEAR
     *
     * @return the value of earning_expense_year.EARNING_YEAR
     *
     * @mbggenerated
     */
    public BigDecimal getEarningYear() {
        return earningYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column earning_expense_year.EARNING_YEAR
     *
     * @param earningYear the value for earning_expense_year.EARNING_YEAR
     *
     * @mbggenerated
     */
    public void setEarningYear(BigDecimal earningYear) {
        this.earningYear = earningYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column earning_expense_year.EXPENSE_YEAR
     *
     * @return the value of earning_expense_year.EXPENSE_YEAR
     *
     * @mbggenerated
     */
    public BigDecimal getExpenseYear() {
        return expenseYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column earning_expense_year.EXPENSE_YEAR
     *
     * @param expenseYear the value for earning_expense_year.EXPENSE_YEAR
     *
     * @mbggenerated
     */
    public void setExpenseYear(BigDecimal expenseYear) {
        this.expenseYear = expenseYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column earning_expense_year.CREATION_DATE
     *
     * @return the value of earning_expense_year.CREATION_DATE
     *
     * @mbggenerated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column earning_expense_year.CREATION_DATE
     *
     * @param creationDate the value for earning_expense_year.CREATION_DATE
     *
     * @mbggenerated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column earning_expense_year.LAST_UPDATE_DATE
     *
     * @return the value of earning_expense_year.LAST_UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column earning_expense_year.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for earning_expense_year.LAST_UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning_expense_year
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", earningExpenseYearId=").append(earningExpenseYearId);
        sb.append(", year=").append(year);
        sb.append(", earningYear=").append(earningYear);
        sb.append(", expenseYear=").append(expenseYear);
        sb.append(", creationDate=").append(creationDate);
        sb.append(", lastUpdateDate=").append(lastUpdateDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}