package com.kanggutang.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class EarningExpenseDay implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column earning_expense_day.EARNING_EXPENSE_DAY_ID
     *
     * @mbggenerated
     */
    private Integer earningExpenseDayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column earning_expense_day.YEAR
     *
     * @mbggenerated
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column earning_expense_day.MONTH
     *
     * @mbggenerated
     */
    private Integer month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column earning_expense_day.DAY
     *
     * @mbggenerated
     */
    private Integer day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column earning_expense_day.EARNING_DAY
     *
     * @mbggenerated
     */
    private BigDecimal earningDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column earning_expense_day.EXPENSE_DAY
     *
     * @mbggenerated
     */
    private BigDecimal expenseDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column earning_expense_day.CREATION_DATE
     *
     * @mbggenerated
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column earning_expense_day.LAST_UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table earning_expense_day
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column earning_expense_day.EARNING_EXPENSE_DAY_ID
     *
     * @return the value of earning_expense_day.EARNING_EXPENSE_DAY_ID
     *
     * @mbggenerated
     */
    public Integer getEarningExpenseDayId() {
        return earningExpenseDayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column earning_expense_day.EARNING_EXPENSE_DAY_ID
     *
     * @param earningExpenseDayId the value for earning_expense_day.EARNING_EXPENSE_DAY_ID
     *
     * @mbggenerated
     */
    public void setEarningExpenseDayId(Integer earningExpenseDayId) {
        this.earningExpenseDayId = earningExpenseDayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column earning_expense_day.YEAR
     *
     * @return the value of earning_expense_day.YEAR
     *
     * @mbggenerated
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column earning_expense_day.YEAR
     *
     * @param year the value for earning_expense_day.YEAR
     *
     * @mbggenerated
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column earning_expense_day.MONTH
     *
     * @return the value of earning_expense_day.MONTH
     *
     * @mbggenerated
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column earning_expense_day.MONTH
     *
     * @param month the value for earning_expense_day.MONTH
     *
     * @mbggenerated
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column earning_expense_day.DAY
     *
     * @return the value of earning_expense_day.DAY
     *
     * @mbggenerated
     */
    public Integer getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column earning_expense_day.DAY
     *
     * @param day the value for earning_expense_day.DAY
     *
     * @mbggenerated
     */
    public void setDay(Integer day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column earning_expense_day.EARNING_DAY
     *
     * @return the value of earning_expense_day.EARNING_DAY
     *
     * @mbggenerated
     */
    public BigDecimal getEarningDay() {
        return earningDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column earning_expense_day.EARNING_DAY
     *
     * @param earningDay the value for earning_expense_day.EARNING_DAY
     *
     * @mbggenerated
     */
    public void setEarningDay(BigDecimal earningDay) {
        this.earningDay = earningDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column earning_expense_day.EXPENSE_DAY
     *
     * @return the value of earning_expense_day.EXPENSE_DAY
     *
     * @mbggenerated
     */
    public BigDecimal getExpenseDay() {
        return expenseDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column earning_expense_day.EXPENSE_DAY
     *
     * @param expenseDay the value for earning_expense_day.EXPENSE_DAY
     *
     * @mbggenerated
     */
    public void setExpenseDay(BigDecimal expenseDay) {
        this.expenseDay = expenseDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column earning_expense_day.CREATION_DATE
     *
     * @return the value of earning_expense_day.CREATION_DATE
     *
     * @mbggenerated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column earning_expense_day.CREATION_DATE
     *
     * @param creationDate the value for earning_expense_day.CREATION_DATE
     *
     * @mbggenerated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column earning_expense_day.LAST_UPDATE_DATE
     *
     * @return the value of earning_expense_day.LAST_UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column earning_expense_day.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for earning_expense_day.LAST_UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning_expense_day
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", earningExpenseDayId=").append(earningExpenseDayId);
        sb.append(", year=").append(year);
        sb.append(", month=").append(month);
        sb.append(", day=").append(day);
        sb.append(", earningDay=").append(earningDay);
        sb.append(", expenseDay=").append(expenseDay);
        sb.append(", creationDate=").append(creationDate);
        sb.append(", lastUpdateDate=").append(lastUpdateDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}