package com.kanggutang.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class EarningExpenseMonth implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column earning_expense_month.EARNING_EXPENSE_MONTH_ID
     *
     * @mbggenerated
     */
    private Integer earningExpenseMonthId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column earning_expense_month.YEAR
     *
     * @mbggenerated
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column earning_expense_month.MONTH
     *
     * @mbggenerated
     */
    private Integer month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column earning_expense_month.EARNING_MONTH
     *
     * @mbggenerated
     */
    private BigDecimal earningMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column earning_expense_month.EXPENSE_MONTH
     *
     * @mbggenerated
     */
    private BigDecimal expenseMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column earning_expense_month.CREATION_DATE
     *
     * @mbggenerated
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column earning_expense_month.LAST_UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table earning_expense_month
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column earning_expense_month.EARNING_EXPENSE_MONTH_ID
     *
     * @return the value of earning_expense_month.EARNING_EXPENSE_MONTH_ID
     *
     * @mbggenerated
     */
    public Integer getEarningExpenseMonthId() {
        return earningExpenseMonthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column earning_expense_month.EARNING_EXPENSE_MONTH_ID
     *
     * @param earningExpenseMonthId the value for earning_expense_month.EARNING_EXPENSE_MONTH_ID
     *
     * @mbggenerated
     */
    public void setEarningExpenseMonthId(Integer earningExpenseMonthId) {
        this.earningExpenseMonthId = earningExpenseMonthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column earning_expense_month.YEAR
     *
     * @return the value of earning_expense_month.YEAR
     *
     * @mbggenerated
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column earning_expense_month.YEAR
     *
     * @param year the value for earning_expense_month.YEAR
     *
     * @mbggenerated
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column earning_expense_month.MONTH
     *
     * @return the value of earning_expense_month.MONTH
     *
     * @mbggenerated
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column earning_expense_month.MONTH
     *
     * @param month the value for earning_expense_month.MONTH
     *
     * @mbggenerated
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column earning_expense_month.EARNING_MONTH
     *
     * @return the value of earning_expense_month.EARNING_MONTH
     *
     * @mbggenerated
     */
    public BigDecimal getEarningMonth() {
        return earningMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column earning_expense_month.EARNING_MONTH
     *
     * @param earningMonth the value for earning_expense_month.EARNING_MONTH
     *
     * @mbggenerated
     */
    public void setEarningMonth(BigDecimal earningMonth) {
        this.earningMonth = earningMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column earning_expense_month.EXPENSE_MONTH
     *
     * @return the value of earning_expense_month.EXPENSE_MONTH
     *
     * @mbggenerated
     */
    public BigDecimal getExpenseMonth() {
        return expenseMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column earning_expense_month.EXPENSE_MONTH
     *
     * @param expenseMonth the value for earning_expense_month.EXPENSE_MONTH
     *
     * @mbggenerated
     */
    public void setExpenseMonth(BigDecimal expenseMonth) {
        this.expenseMonth = expenseMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column earning_expense_month.CREATION_DATE
     *
     * @return the value of earning_expense_month.CREATION_DATE
     *
     * @mbggenerated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column earning_expense_month.CREATION_DATE
     *
     * @param creationDate the value for earning_expense_month.CREATION_DATE
     *
     * @mbggenerated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column earning_expense_month.LAST_UPDATE_DATE
     *
     * @return the value of earning_expense_month.LAST_UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column earning_expense_month.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for earning_expense_month.LAST_UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table earning_expense_month
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", earningExpenseMonthId=").append(earningExpenseMonthId);
        sb.append(", year=").append(year);
        sb.append(", month=").append(month);
        sb.append(", earningMonth=").append(earningMonth);
        sb.append(", expenseMonth=").append(expenseMonth);
        sb.append(", creationDate=").append(creationDate);
        sb.append(", lastUpdateDate=").append(lastUpdateDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}