package com.kanggutang.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Expense implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense.EXPENSE_ID
     *
     * @mbggenerated
     */
    private Integer expenseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense.EXPENSE_TYPE
     *
     * @mbggenerated
     */
    private Integer expenseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense.EXPENSE_NAME
     *
     * @mbggenerated
     */
    private String expenseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense.EXPENSE_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal expenseAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense.YEAR
     *
     * @mbggenerated
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense.MONTH
     *
     * @mbggenerated
     */
    private Integer month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense.DAY
     *
     * @mbggenerated
     */
    private Integer day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense.CREATION_DATE
     *
     * @mbggenerated
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense.CREATED_BY
     *
     * @mbggenerated
     */
    private Integer createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense.LAST_UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense.LAST_UPDATED_BY
     *
     * @mbggenerated
     */
    private Integer lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table expense
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense.EXPENSE_ID
     *
     * @return the value of expense.EXPENSE_ID
     *
     * @mbggenerated
     */
    public Integer getExpenseId() {
        return expenseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense.EXPENSE_ID
     *
     * @param expenseId the value for expense.EXPENSE_ID
     *
     * @mbggenerated
     */
    public void setExpenseId(Integer expenseId) {
        this.expenseId = expenseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense.EXPENSE_TYPE
     *
     * @return the value of expense.EXPENSE_TYPE
     *
     * @mbggenerated
     */
    public Integer getExpenseType() {
        return expenseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense.EXPENSE_TYPE
     *
     * @param expenseType the value for expense.EXPENSE_TYPE
     *
     * @mbggenerated
     */
    public void setExpenseType(Integer expenseType) {
        this.expenseType = expenseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense.EXPENSE_NAME
     *
     * @return the value of expense.EXPENSE_NAME
     *
     * @mbggenerated
     */
    public String getExpenseName() {
        return expenseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense.EXPENSE_NAME
     *
     * @param expenseName the value for expense.EXPENSE_NAME
     *
     * @mbggenerated
     */
    public void setExpenseName(String expenseName) {
        this.expenseName = expenseName == null ? null : expenseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense.EXPENSE_AMOUNT
     *
     * @return the value of expense.EXPENSE_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getExpenseAmount() {
        return expenseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense.EXPENSE_AMOUNT
     *
     * @param expenseAmount the value for expense.EXPENSE_AMOUNT
     *
     * @mbggenerated
     */
    public void setExpenseAmount(BigDecimal expenseAmount) {
        this.expenseAmount = expenseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense.YEAR
     *
     * @return the value of expense.YEAR
     *
     * @mbggenerated
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense.YEAR
     *
     * @param year the value for expense.YEAR
     *
     * @mbggenerated
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense.MONTH
     *
     * @return the value of expense.MONTH
     *
     * @mbggenerated
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense.MONTH
     *
     * @param month the value for expense.MONTH
     *
     * @mbggenerated
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense.DAY
     *
     * @return the value of expense.DAY
     *
     * @mbggenerated
     */
    public Integer getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense.DAY
     *
     * @param day the value for expense.DAY
     *
     * @mbggenerated
     */
    public void setDay(Integer day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense.REMARK
     *
     * @return the value of expense.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense.REMARK
     *
     * @param remark the value for expense.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense.CREATION_DATE
     *
     * @return the value of expense.CREATION_DATE
     *
     * @mbggenerated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense.CREATION_DATE
     *
     * @param creationDate the value for expense.CREATION_DATE
     *
     * @mbggenerated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense.CREATED_BY
     *
     * @return the value of expense.CREATED_BY
     *
     * @mbggenerated
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense.CREATED_BY
     *
     * @param createdBy the value for expense.CREATED_BY
     *
     * @mbggenerated
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense.LAST_UPDATE_DATE
     *
     * @return the value of expense.LAST_UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for expense.LAST_UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense.LAST_UPDATED_BY
     *
     * @return the value of expense.LAST_UPDATED_BY
     *
     * @mbggenerated
     */
    public Integer getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for expense.LAST_UPDATED_BY
     *
     * @mbggenerated
     */
    public void setLastUpdatedBy(Integer lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", expenseId=").append(expenseId);
        sb.append(", expenseType=").append(expenseType);
        sb.append(", expenseName=").append(expenseName);
        sb.append(", expenseAmount=").append(expenseAmount);
        sb.append(", year=").append(year);
        sb.append(", month=").append(month);
        sb.append(", day=").append(day);
        sb.append(", remark=").append(remark);
        sb.append(", creationDate=").append(creationDate);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", lastUpdateDate=").append(lastUpdateDate);
        sb.append(", lastUpdatedBy=").append(lastUpdatedBy);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}