package com.kanggutang.model;

import java.io.Serializable;
import java.util.Date;

public class PermissionRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_role.PERMISSION_ROLE_ID
     *
     * @mbggenerated
     */
    private Integer permissionRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_role.PERMISSION_ID
     *
     * @mbggenerated
     */
    private Integer permissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_role.ROLE_ID
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_role.CREATION_DATE
     *
     * @mbggenerated
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table permission_role
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_role.PERMISSION_ROLE_ID
     *
     * @return the value of permission_role.PERMISSION_ROLE_ID
     *
     * @mbggenerated
     */
    public Integer getPermissionRoleId() {
        return permissionRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_role.PERMISSION_ROLE_ID
     *
     * @param permissionRoleId the value for permission_role.PERMISSION_ROLE_ID
     *
     * @mbggenerated
     */
    public void setPermissionRoleId(Integer permissionRoleId) {
        this.permissionRoleId = permissionRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_role.PERMISSION_ID
     *
     * @return the value of permission_role.PERMISSION_ID
     *
     * @mbggenerated
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_role.PERMISSION_ID
     *
     * @param permissionId the value for permission_role.PERMISSION_ID
     *
     * @mbggenerated
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_role.ROLE_ID
     *
     * @return the value of permission_role.ROLE_ID
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_role.ROLE_ID
     *
     * @param roleId the value for permission_role.ROLE_ID
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_role.CREATION_DATE
     *
     * @return the value of permission_role.CREATION_DATE
     *
     * @mbggenerated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_role.CREATION_DATE
     *
     * @param creationDate the value for permission_role.CREATION_DATE
     *
     * @mbggenerated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", permissionRoleId=").append(permissionRoleId);
        sb.append(", permissionId=").append(permissionId);
        sb.append(", roleId=").append(roleId);
        sb.append(", creationDate=").append(creationDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}